// <auto-generated />
using System;
using GameStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameStore.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20221108151728_RemoveCustomerPassword")]
    partial class RemoveCustomerPassword
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CustomerEvent", b =>
                {
                    b.Property<int>("Customerid")
                        .HasColumnType("int");

                    b.Property<int>("Eventid")
                        .HasColumnType("int");

                    b.HasKey("Customerid", "Eventid")
                        .HasName("PK__Customer__333907D60F8269FF");

                    b.HasIndex("Eventid");

                    b.ToTable("CustomerEvent", (string)null);
                });

            modelBuilder.Entity("GameCategory", b =>
                {
                    b.Property<int>("Gameid")
                        .HasColumnType("int");

                    b.Property<int>("Categoryid")
                        .HasColumnType("int");

                    b.HasKey("Gameid", "Categoryid")
                        .HasName("PK__Game_Cat__0B57EBB7A12BD34A");

                    b.HasIndex("Categoryid");

                    b.ToTable("GameCategory", (string)null);
                });

            modelBuilder.Entity("GameFeatureGame", b =>
                {
                    b.Property<int>("GameFeatureid")
                        .HasColumnType("int");

                    b.Property<int>("Gameid")
                        .HasColumnType("int");

                    b.HasKey("GameFeatureid", "Gameid")
                        .HasName("PK__GameFeat__0E2BBB9711BBC777");

                    b.HasIndex("Gameid");

                    b.ToTable("GameFeatureGame", (string)null);
                });

            modelBuilder.Entity("GameStore.Data.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("CategoryId");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Shooter"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Fighting"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Stealth"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "RPG"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Survival"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Platformer"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "MOBA"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Simulator"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Puzzler"
                        });
                });

            modelBuilder.Entity("GameStore.Data.CreditCard", b =>
                {
                    b.Property<int>("CreditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("credit_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CreditId"), 1L, 1);

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cardName");

                    b.Property<int>("CardNumber")
                        .HasColumnType("int")
                        .HasColumnName("cardNumber");

                    b.Property<int>("CustId")
                        .HasColumnType("int")
                        .HasColumnName("cust_id");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("expirationDate");

                    b.HasKey("CreditId")
                        .HasName("PK__CreditCa__C15A9C36A58DE279");

                    b.HasIndex("CustId");

                    b.ToTable("CreditCard", (string)null);
                });

            modelBuilder.Entity("GameStore.Data.Customer", b =>
                {
                    b.Property<int>("CustId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cust_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustId"), 1L, 1);

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("firstName");

                    b.Property<int?>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("lastName");

                    b.Property<int?>("MailingAddressId")
                        .HasColumnType("int")
                        .HasColumnName("mailingAddress_id");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("PreferedCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("preferedCategory_id");

                    b.Property<int?>("PreferedPlatformId")
                        .HasColumnType("int")
                        .HasColumnName("preferedPlatform_id");

                    b.Property<bool?>("RecievePromotion")
                        .HasColumnType("bit")
                        .HasColumnName("recievePromotion");

                    b.Property<int?>("ShippingAddressId")
                        .HasColumnType("int")
                        .HasColumnName("shippingAddress_id");

                    b.HasKey("CustId")
                        .HasName("PK__Customer__A1B71F90C6489007");

                    b.HasIndex("MailingAddressId");

                    b.HasIndex("PreferedCategoryId");

                    b.HasIndex("PreferedPlatformId");

                    b.HasIndex("ShippingAddressId");

                    b.HasIndex(new[] { "Email" }, "UQ__Customer__AB6E6164661522CF")
                        .IsUnique();

                    b.HasIndex(new[] { "Nickname" }, "UQ__Customer__CC6CD17E283CABFD")
                        .IsUnique();

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("GameStore.Data.CustomerEvent", b =>
                {
                    b.Property<int>("Customerid")
                        .HasColumnType("int");

                    b.Property<int>("Eventid")
                        .HasColumnType("int");

                    b.HasKey("Customerid", "Eventid");

                    b.HasIndex("Eventid");

                    b.ToTable("CustomerEvents");
                });

            modelBuilder.Entity("GameStore.Data.Employee", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("emp_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.HasKey("EmpId")
                        .HasName("PK__Employee__1299A861977CC9A6");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("GameStore.Data.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"), 1L, 1);

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Duration")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("duration");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("EventId");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("GameStore.Data.FriendsFamily", b =>
                {
                    b.Property<int>("FriendId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("friend_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FriendId"), 1L, 1);

                    b.Property<int>("CustId1")
                        .HasColumnType("int")
                        .HasColumnName("cust_id1");

                    b.Property<int>("CustId2")
                        .HasColumnType("int")
                        .HasColumnName("cust_id2");

                    b.Property<DateTime>("DateConnected")
                        .HasColumnType("datetime")
                        .HasColumnName("dateConnected");

                    b.Property<bool>("IsFamily")
                        .HasColumnType("bit")
                        .HasColumnName("isFamily");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("FriendId")
                        .HasName("PK__FriendsF__3FA1E155F831F53C");

                    b.HasIndex("CustId1");

                    b.HasIndex("CustId2");

                    b.ToTable("FriendsFamily", (string)null);
                });

            modelBuilder.Entity("GameStore.Data.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("game_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<bool?>("Digital")
                        .HasColumnType("bit")
                        .HasColumnName("digital");

                    b.Property<int?>("Discount")
                        .HasColumnType("int")
                        .HasColumnName("discount");

                    b.Property<int?>("GameStudio")
                        .HasColumnType("int")
                        .HasColumnName("gameStudio");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("Pquantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(19,2)")
                        .HasColumnName("price");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime")
                        .HasColumnName("releaseDate");

                    b.HasKey("GameId");

                    b.ToTable("Game", (string)null);
                });

            modelBuilder.Entity("GameStore.Data.GameCategory", b =>
                {
                    b.Property<int>("Gameid")
                        .HasColumnType("int");

                    b.Property<int>("Categoryid")
                        .HasColumnType("int");

                    b.HasKey("Gameid", "Categoryid");

                    b.HasIndex("Categoryid");

                    b.ToTable("GameCategories");
                });

            modelBuilder.Entity("GameStore.Data.GameFeature", b =>
                {
                    b.Property<int>("FeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("feature_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeatureId"), 1L, 1);

                    b.Property<string>("Feature")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("feature");

                    b.HasKey("FeatureId")
                        .HasName("PK__GameFeat__7906CBD7BF1F29A9");

                    b.ToTable("GameFeature", (string)null);
                });

            modelBuilder.Entity("GameStore.Data.GameFeatureGame", b =>
                {
                    b.Property<int>("GameFeatureid")
                        .HasColumnType("int");

                    b.Property<int>("Gameid")
                        .HasColumnType("int");

                    b.HasKey("GameFeatureid", "Gameid");

                    b.HasIndex("Gameid");

                    b.ToTable("GameFeatureGames");
                });

            modelBuilder.Entity("GameStore.Data.GameImage", b =>
                {
                    b.Property<int>("GameImgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("gameImg_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameImgId"), 1L, 1);

                    b.Property<string>("Extention")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("extention");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("game_id");

                    b.Property<bool>("IsCoverImage")
                        .HasColumnType("bit")
                        .HasColumnName("isCoverImage");

                    b.Property<string>("Path")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("path");

                    b.HasKey("GameImgId")
                        .HasName("PK__GameImag__132575EA33968AE7");

                    b.HasIndex("GameId");

                    b.ToTable("GameImage", (string)null);
                });

            modelBuilder.Entity("GameStore.Data.MailingAddress", b =>
                {
                    b.Property<int>("MailingAddressId")
                        .HasColumnType("int")
                        .HasColumnName("mailingAddressId");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(55)
                        .IsUnicode(false)
                        .HasColumnType("varchar(55)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<int>("Province")
                        .HasColumnType("int");

                    b.HasKey("MailingAddressId");

                    b.ToTable("MailingAddress", (string)null);
                });

            modelBuilder.Entity("GameStore.Data.Merchandise", b =>
                {
                    b.Property<int>("MerchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("merch_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MerchId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<int?>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("game_id");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(19,2)")
                        .HasColumnName("price");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("MerchId")
                        .HasName("PK__Merchand__1937E9C0E88FCC6F");

                    b.ToTable("Merchandise", (string)null);
                });

            modelBuilder.Entity("GameStore.Data.MerchandiseImage", b =>
                {
                    b.Property<int>("MerchImgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("merchImg_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MerchImgId"), 1L, 1);

                    b.Property<string>("Extention")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("extention");

                    b.Property<int>("MerchandiseId")
                        .HasColumnType("int")
                        .HasColumnName("merchandise_id");

                    b.Property<string>("Path")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("path");

                    b.HasKey("MerchImgId")
                        .HasName("PK__Merchand__4D99D94A9EAE7002");

                    b.HasIndex("MerchandiseId");

                    b.ToTable("MerchandiseImage", (string)null);
                });

            modelBuilder.Entity("GameStore.Data.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"), 1L, 1);

                    b.Property<int>("CustId")
                        .HasColumnType("int")
                        .HasColumnName("cust_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime")
                        .HasColumnName("date");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("game_id");

                    b.Property<bool>("IsShipped")
                        .HasColumnType("bit")
                        .HasColumnName("isShipped");

                    b.Property<int>("MerchandiseId")
                        .HasColumnType("int")
                        .HasColumnName("merchandise_id");

                    b.Property<string>("OrderNo")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("order_no");

                    b.HasKey("OrderId");

                    b.HasIndex("CustId");

                    b.HasIndex("GameId");

                    b.HasIndex("MerchandiseId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("GameStore.Data.Platform", b =>
                {
                    b.Property<int>("PlatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("platform_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlatformId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("PlatformId");

                    b.ToTable("Platform", (string)null);

                    b.HasData(
                        new
                        {
                            PlatformId = 1,
                            Name = "PC"
                        },
                        new
                        {
                            PlatformId = 2,
                            Name = "Xbox"
                        },
                        new
                        {
                            PlatformId = 3,
                            Name = "PlayStation"
                        },
                        new
                        {
                            PlatformId = 4,
                            Name = "Nintendo"
                        },
                        new
                        {
                            PlatformId = 5,
                            Name = "VR"
                        },
                        new
                        {
                            PlatformId = 6,
                            Name = "Mobile"
                        },
                        new
                        {
                            PlatformId = 7,
                            Name = "Steam OS"
                        });
                });

            modelBuilder.Entity("GameStore.Data.PlatformGame", b =>
                {
                    b.Property<int>("Platformid")
                        .HasColumnType("int");

                    b.Property<int>("Gameid")
                        .HasColumnType("int");

                    b.HasKey("Platformid", "Gameid");

                    b.HasIndex("Gameid");

                    b.ToTable("PlatformGames");
                });

            modelBuilder.Entity("GameStore.Data.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("review_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"), 1L, 1);

                    b.Property<int>("CustId")
                        .HasColumnType("int")
                        .HasColumnName("cust_id");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("game_id");

                    b.Property<int>("Rate")
                        .HasColumnType("int")
                        .HasColumnName("rate");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("ReviewId");

                    b.HasIndex("CustId");

                    b.HasIndex("GameId");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("GameStore.Data.ReviewImage", b =>
                {
                    b.Property<int>("ReviewImgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reviewImg_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewImgId"), 1L, 1);

                    b.Property<string>("Extention")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("extention");

                    b.Property<string>("Path")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("path");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int")
                        .HasColumnName("review_id");

                    b.HasKey("ReviewImgId")
                        .HasName("PK__ReviewIm__ADCB53FF60CE66D7");

                    b.HasIndex("ReviewId");

                    b.ToTable("ReviewImage", (string)null);
                });

            modelBuilder.Entity("GameStore.Data.ShippingAddress", b =>
                {
                    b.Property<int>("ShippingAddressId")
                        .HasColumnType("int")
                        .HasColumnName("shippingAddressId");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(55)
                        .IsUnicode(false)
                        .HasColumnType("varchar(55)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<int>("Province")
                        .HasColumnType("int");

                    b.HasKey("ShippingAddressId");

                    b.ToTable("ShippingAddress", (string)null);
                });

            modelBuilder.Entity("GameStore.Data.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GameStore.Data.WishList", b =>
                {
                    b.Property<int>("WishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("wish_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WishId"), 1L, 1);

                    b.Property<int>("CustId")
                        .HasColumnType("int")
                        .HasColumnName("cust_id");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("game_id");

                    b.Property<int>("MerchandiseId")
                        .HasColumnType("int")
                        .HasColumnName("merchandise_id");

                    b.HasKey("WishId")
                        .HasName("PK__WishList__4F227CA0D99D4B73");

                    b.HasIndex("CustId");

                    b.HasIndex("GameId");

                    b.HasIndex("MerchandiseId");

                    b.ToTable("WishList", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PlatformGame", b =>
                {
                    b.Property<int>("Platformid")
                        .HasColumnType("int");

                    b.Property<int>("Gameid")
                        .HasColumnType("int");

                    b.HasKey("Platformid", "Gameid")
                        .HasName("PK__Platform__B7F882CFAE338AEA");

                    b.HasIndex("Gameid");

                    b.ToTable("PlatformGame", (string)null);
                });

            modelBuilder.Entity("CustomerEvent", b =>
                {
                    b.HasOne("GameStore.Data.Customer", null)
                        .WithMany()
                        .HasForeignKey("Customerid")
                        .IsRequired()
                        .HasConstraintName("FKCustomer_E75975");

                    b.HasOne("GameStore.Data.Event", null)
                        .WithMany()
                        .HasForeignKey("Eventid")
                        .IsRequired()
                        .HasConstraintName("FKCustomer_E485607");
                });

            modelBuilder.Entity("GameCategory", b =>
                {
                    b.HasOne("GameStore.Data.Category", null)
                        .WithMany()
                        .HasForeignKey("Categoryid")
                        .IsRequired()
                        .HasConstraintName("FKGame_Categ786403");

                    b.HasOne("GameStore.Data.Game", null)
                        .WithMany()
                        .HasForeignKey("Gameid")
                        .IsRequired()
                        .HasConstraintName("FKGame_Categ26396");
                });

            modelBuilder.Entity("GameFeatureGame", b =>
                {
                    b.HasOne("GameStore.Data.GameFeature", null)
                        .WithMany()
                        .HasForeignKey("GameFeatureid")
                        .IsRequired()
                        .HasConstraintName("FKGameFeatur415415");

                    b.HasOne("GameStore.Data.Game", null)
                        .WithMany()
                        .HasForeignKey("Gameid")
                        .IsRequired()
                        .HasConstraintName("FKGameFeatur387831");
                });

            modelBuilder.Entity("GameStore.Data.CreditCard", b =>
                {
                    b.HasOne("GameStore.Data.Customer", "Cust")
                        .WithMany("CreditCards")
                        .HasForeignKey("CustId")
                        .IsRequired()
                        .HasConstraintName("FKCreditCard326673");

                    b.Navigation("Cust");
                });

            modelBuilder.Entity("GameStore.Data.Customer", b =>
                {
                    b.HasOne("GameStore.Data.MailingAddress", "MailingAddress")
                        .WithMany("Customers")
                        .HasForeignKey("MailingAddressId")
                        .HasConstraintName("FK_Customer_MailingAddress");

                    b.HasOne("GameStore.Data.Category", "PreferedCategory")
                        .WithMany("Customers")
                        .HasForeignKey("PreferedCategoryId")
                        .HasConstraintName("FKCustomer578024");

                    b.HasOne("GameStore.Data.Platform", "PreferedPlatform")
                        .WithMany("Customers")
                        .HasForeignKey("PreferedPlatformId")
                        .HasConstraintName("FKCustomer55737");

                    b.HasOne("GameStore.Data.ShippingAddress", "ShippingAddress")
                        .WithMany("Customers")
                        .HasForeignKey("ShippingAddressId")
                        .HasConstraintName("FK_Customer_ShippingAddress");

                    b.Navigation("MailingAddress");

                    b.Navigation("PreferedCategory");

                    b.Navigation("PreferedPlatform");

                    b.Navigation("ShippingAddress");
                });

            modelBuilder.Entity("GameStore.Data.CustomerEvent", b =>
                {
                    b.HasOne("GameStore.Data.Customer", "Customer")
                        .WithMany("CustomerEvents")
                        .HasForeignKey("Customerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Data.Event", "Event")
                        .WithMany("CustomerEvents")
                        .HasForeignKey("Eventid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("GameStore.Data.FriendsFamily", b =>
                {
                    b.HasOne("GameStore.Data.Customer", "CustId1Navigation")
                        .WithMany("FriendsFamilyCustId1Navigations")
                        .HasForeignKey("CustId1")
                        .IsRequired()
                        .HasConstraintName("FKFriendsFam820474");

                    b.HasOne("GameStore.Data.Customer", "CustId2Navigation")
                        .WithMany("FriendsFamilyCustId2Navigations")
                        .HasForeignKey("CustId2")
                        .IsRequired()
                        .HasConstraintName("FKFriendsFam820475");

                    b.Navigation("CustId1Navigation");

                    b.Navigation("CustId2Navigation");
                });

            modelBuilder.Entity("GameStore.Data.GameCategory", b =>
                {
                    b.HasOne("GameStore.Data.Category", "Category")
                        .WithMany("GameCategories")
                        .HasForeignKey("Categoryid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Data.Game", "Game")
                        .WithMany("GameCategories")
                        .HasForeignKey("Gameid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GameStore.Data.GameFeatureGame", b =>
                {
                    b.HasOne("GameStore.Data.GameFeature", "GameFeature")
                        .WithMany("GameFeatureGames")
                        .HasForeignKey("GameFeatureid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Data.Game", "Game")
                        .WithMany("GameFeatureGames")
                        .HasForeignKey("Gameid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("GameFeature");
                });

            modelBuilder.Entity("GameStore.Data.GameImage", b =>
                {
                    b.HasOne("GameStore.Data.Game", "Game")
                        .WithMany("GameImages")
                        .HasForeignKey("GameId")
                        .IsRequired()
                        .HasConstraintName("FKGameImage381528");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GameStore.Data.MerchandiseImage", b =>
                {
                    b.HasOne("GameStore.Data.Merchandise", "Merchandise")
                        .WithMany("MerchandiseImages")
                        .HasForeignKey("MerchandiseId")
                        .IsRequired()
                        .HasConstraintName("FKMerchandis483326");

                    b.Navigation("Merchandise");
                });

            modelBuilder.Entity("GameStore.Data.Order", b =>
                {
                    b.HasOne("GameStore.Data.Customer", "Cust")
                        .WithMany("Orders")
                        .HasForeignKey("CustId")
                        .IsRequired()
                        .HasConstraintName("FKOrder861201");

                    b.HasOne("GameStore.Data.Game", "Game")
                        .WithMany("Orders")
                        .HasForeignKey("GameId")
                        .IsRequired()
                        .HasConstraintName("FKOrder547560");

                    b.HasOne("GameStore.Data.Merchandise", "Merchandise")
                        .WithMany("Orders")
                        .HasForeignKey("MerchandiseId")
                        .IsRequired()
                        .HasConstraintName("FKOrder609133");

                    b.Navigation("Cust");

                    b.Navigation("Game");

                    b.Navigation("Merchandise");
                });

            modelBuilder.Entity("GameStore.Data.PlatformGame", b =>
                {
                    b.HasOne("GameStore.Data.Game", "Game")
                        .WithMany("PlatformGames")
                        .HasForeignKey("Gameid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Data.Platform", "Platform")
                        .WithMany("PlatformGames")
                        .HasForeignKey("Platformid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("GameStore.Data.Review", b =>
                {
                    b.HasOne("GameStore.Data.Customer", "Cust")
                        .WithMany("Reviews")
                        .HasForeignKey("CustId")
                        .IsRequired()
                        .HasConstraintName("FKReview172984");

                    b.HasOne("GameStore.Data.Game", "Game")
                        .WithMany("Reviews")
                        .HasForeignKey("GameId")
                        .IsRequired()
                        .HasConstraintName("FKReview486625");

                    b.Navigation("Cust");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GameStore.Data.ReviewImage", b =>
                {
                    b.HasOne("GameStore.Data.Review", "Review")
                        .WithMany("ReviewImages")
                        .HasForeignKey("ReviewId")
                        .IsRequired()
                        .HasConstraintName("FKReviewImag856029");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("GameStore.Data.WishList", b =>
                {
                    b.HasOne("GameStore.Data.Customer", "Cust")
                        .WithMany("WishLists")
                        .HasForeignKey("CustId")
                        .IsRequired()
                        .HasConstraintName("FKWishList705462");

                    b.HasOne("GameStore.Data.Game", "Game")
                        .WithMany("WishLists")
                        .HasForeignKey("GameId")
                        .IsRequired()
                        .HasConstraintName("FKWishList952486");

                    b.HasOne("GameStore.Data.Merchandise", "Merchandise")
                        .WithMany("WishLists")
                        .HasForeignKey("MerchandiseId")
                        .IsRequired()
                        .HasConstraintName("FKWishList795792");

                    b.Navigation("Cust");

                    b.Navigation("Game");

                    b.Navigation("Merchandise");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GameStore.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GameStore.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GameStore.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlatformGame", b =>
                {
                    b.HasOne("GameStore.Data.Game", null)
                        .WithMany()
                        .HasForeignKey("Gameid")
                        .IsRequired()
                        .HasConstraintName("FKPlatform_G103358");

                    b.HasOne("GameStore.Data.Platform", null)
                        .WithMany()
                        .HasForeignKey("Platformid")
                        .IsRequired()
                        .HasConstraintName("FKPlatform_G477683");
                });

            modelBuilder.Entity("GameStore.Data.Category", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("GameCategories");
                });

            modelBuilder.Entity("GameStore.Data.Customer", b =>
                {
                    b.Navigation("CreditCards");

                    b.Navigation("CustomerEvents");

                    b.Navigation("FriendsFamilyCustId1Navigations");

                    b.Navigation("FriendsFamilyCustId2Navigations");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");

                    b.Navigation("WishLists");
                });

            modelBuilder.Entity("GameStore.Data.Event", b =>
                {
                    b.Navigation("CustomerEvents");
                });

            modelBuilder.Entity("GameStore.Data.Game", b =>
                {
                    b.Navigation("GameCategories");

                    b.Navigation("GameFeatureGames");

                    b.Navigation("GameImages");

                    b.Navigation("Orders");

                    b.Navigation("PlatformGames");

                    b.Navigation("Reviews");

                    b.Navigation("WishLists");
                });

            modelBuilder.Entity("GameStore.Data.GameFeature", b =>
                {
                    b.Navigation("GameFeatureGames");
                });

            modelBuilder.Entity("GameStore.Data.MailingAddress", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("GameStore.Data.Merchandise", b =>
                {
                    b.Navigation("MerchandiseImages");

                    b.Navigation("Orders");

                    b.Navigation("WishLists");
                });

            modelBuilder.Entity("GameStore.Data.Platform", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("PlatformGames");
                });

            modelBuilder.Entity("GameStore.Data.Review", b =>
                {
                    b.Navigation("ReviewImages");
                });

            modelBuilder.Entity("GameStore.Data.ShippingAddress", b =>
                {
                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
